### PR TITLE
These don't need to be imported

### PR DESCRIPTION
**Pull request by ryannair05**
I believe there are more things that can be removed as they are unnecessary but that is something to be looked upon later.

### CODE REVIEW

**Comment by ryannair05** [comment]
Actually, they might need to be enabled. I'm not sure as I removed it in LittleXS and the padlock works for some people but not for everyone. It's like 80/20 that it works. I am thinking maybe if another tweak imports them then they don't need to be imported here but that doesn't make sense, to me at least?

**Comment by SyedMuhammadAhmad** [comment]
Ok it will be help if you ask the developer

**Comment by SniperGER** [comment]
These imports are required on a per-tweak basis since the compiler doesn't know about any other tweaks while building.
In this case, ```substrate.h``` is required for patchfinder64 to work, to be exact ```MSFindSymbol``` and ```MSHookFunction``` (probably not even for the least).

I might have carried over ```stdint.h``` from MGSpoof accidentally , and this one is actually not needed at all since compiling ProudLock without it works just fine.

**Comment by ryannair05** [comment]
So I have confirmed that ```#include <substrate.h>``` is not needed; though, I still need to do more testing for ```stdint.h```

**Pull request closed without merging**
